### PR TITLE
Added support to custom delimiters

### LINKED ISSUE #64: Support using custom delimiters
Hi ! First of all thanks for this awesome lib !

Do you have any plans on implementing a way to provide custom delimiters ? Either at compile time or at runtime.

This feature does not exist in Tera, and Askama’s approach makes it impossi ble to have runtime provided templates. I am writing a CLI to parse and render jinja2 templates using `[[ … ]]`, `[% … %]` and `[# … #]` to avoid conflicting with other templating languages used in the files I am processing.

Thanks in advance !

### PR DESCRIPTION
**Pull request by morenol**
This PRs adds support for using custom delimiters. It is behind a feature flag (because it includes `aho-corasick` as it was mentioned in https://github.com/mitsuhiko/minijinja/issues/64 

Fixes #64

### CODE REVIEW

**Comment by morenol** [comment]
- [x] `Copy` on `Syntax`: Updated Syntax to internally have `Cow<'static, str>`
- [ ] `Syntax` on `Environment` vs `Source`:  I think that we can move Syntax to only be on `Source` but then I am not sure how to proceed when de `Source` feature is not enabled an `custom_delimiters` is enabled. Maybe we should add `source` feature as a dependency of `custom_delimiter`? what do you think?
- [ ] `Syntax::new`: Regarding this, I think that we can proceed with this but then only make the internal fields public if the feature is enabled. What do you think?

**Comment by morenol** [comment]
Maybe `custom_syntax` is a better name than `custom_delimiters`?

**Comment by mitsuhiko** [comment]
Now that the syntax is not `Copy` any more, I think `find_marker` can be improved greatly. When the custom-delimiters feature is enabled, the `AhoCorasick` can be cached on the `Syntax`. I would basically make `find_marker` be a method on the syntax object.

**Comment by mitsuhiko** [comment]
I pushed up a change that moves the syntax out of the environment. The fact that the parser/lexer require a clone of the syntax is unfortunate but I presume this simplifies lifetimes. I will have a look if I can optimize this.

**Comment by morenol** [comment]
> I think I will merge this with some minor modifications later today.

Thanks! I like the idea of caching the AhoCorasick instance. Maybe instead of making public the fields we could use a method to create the syntax where we do that. Maybe we could check there that all the fields of Syntax should be unique

**Comment by morenol** [comment]
@mitsuhiko thanks, you can give it another look, and updated anything that you thing that is needed in order to merge this.

Thanks for this library!

**Comment by mitsuhiko** [comment]
Thank you. I will do some minor changes and then merge it.

**Comment by mitsuhiko** [comment]
I won't be able to finish this today. I added a test with a config that turns out to be causing the lexer to go into an endless loop

```rust
#[test]
#[cfg(feature = "custom_delimiters")]
fn test_custom_syntax() {
    let mut env = Environment::new();
    env.set_syntax(minijinja::Syntax {
        block_start: "{".into(),
        block_end: "}".into(),
        variable_start: "${".into(),
        variable_end: "}".into(),
        comment_start: "{*".into(),
        comment_end: "*}".into(),
    })
    .unwrap();

    // this on the other hand is okay
    let value = env
        .render_str("{for x in range(3)}${x}{endfor}{* nothing *}", ())
        .unwrap();
    assert_eq!(value, r"123");
}

```

**Comment by mitsuhiko** [comment]
I see the problem. The delimiters are assumed to have the same length with the original delimiters which is obviously not necessary. The hardcoded offsets need to be adjusted, same with the manual slicing.

**Comment by morenol** [comment]
> I see the problem. The delimiters are assumed to have the same length with the original delimiters which is obviously not necessary. The hardcoded offsets need to be adjusted, same with the manual slicing.

I can work on it

**Comment by mitsuhiko** [comment]
@morenol i have to tap out now. I fixed a few instances of this, but fundamentally the matching between comment/block/variable has to be longest to shortest. So the test checked in still does not pass because `{*` is the string for comments and `{` is the one for blocks, so it tries to parse a block first. Also generally I made the code quite ugly now :)

**Comment by morenol** [comment]
> I think the correct way to fix this would be to have a method on the `Syntax` like this:

Maybe using `aho_corasick::MatchKind::LeftmostLongest` could fix the issue?

**Pull request merged**
