### PR TITLE
Add Stubs for Python Interface

### LINKED ISSUE #572: Relaxing maturin version pin for minijinja-py
### Discussed in https://github.com/mitsuhiko/minijinja/discussions/566

<div type='discussions-op-text'>

<sup>Originally posted by **synapticarbors** August 27, 2024</sup>
Currently `minijinja-py` has a pyproject.toml defining:

```toml
[build-system]
requires = ["maturin>=0.15,<0.16"]
```

I was wondering if there were any blockers that would make it difficult to relax the `maturin` constraint to allow for newer versions? The last compatible maturin release (0.15.3) was from May 2023, and the latest version is 1.7.1.</div>

### PR DESCRIPTION
**Pull request by max-muoto**
This PR adds public facing type stubs to improve usability to give Python users intellisense and the ability to use `minininja` in projects with type-checking enabled. [Pyright](https://github.com/microsoft/pyright) is used for basic linting/ensuring these stubs are valid across all versions of Python minijijna supports (3.9+).

If this isn't something you're interested in maintaining for the time being, I'm happy to just put this on [`typeshed`](https://github.com/python/typeshed) instead.

Also fixes #572

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I think this is probably a good idea to add but the question is how to make sure it stays up to date and correct.

**Comment by max-muoto** [comment]
> I think this is probably a good idea to add but the question is how to make sure it stays up to date and correct.

I think we could try out using [Stubtest](https://mypy.readthedocs.io/en/stable/stubtest.html) and see if it would allow us to at least have some basic level of correctness (makings sure the we don't miss any new functions/leave old stub). Any thoughts?

**Comment by mitsuhiko** [comment]
I would like to include this but the pyright CI step fails.

**Comment by max-muoto** [comment]
> I would like to include this but the pyright CI step fails.

If you're able to approve the pipelines again, I think things should be working now.

**Pull request merged**
