### PR TITLE
Objects 2.0

### PR DESCRIPTION
**Pull request by SergioBenitez**
This is an (incomplete) implementation of https://github.com/mitsuhiko/minijinja/pull/400#issuecomment-1987382640. I have not tested this whatsoever. In fact, tests don't compile. However, the main lib does, and all previous functionality has been reimplemented, so putting this up here to move the conversation along.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
This looks really nice. I don't want to go and nitpick at this point because it's too early, but in general I'm quite in favor of this.

**Comment by SergioBenitez** [comment]
Awesome. Glad to hear. It's definitely cleaned up a ton of internal code.

I've gotten most tests to pass now. Should have all tests passing soon. Once that's done, will likely do a pass through the changes to clean things up. Then we can get to the details.

**Comment by SergioBenitez** [comment]
All tests in the core lib are now passing!

**Comment by SergioBenitez** [comment]
@mitsuhiko Any chance to get a proper review? I should state that I _really_ don't want to update the other crates. They're using a lot of `unsafe` and integrating with a lot of things that I'm not familiar with. If you could handle updating those, that'd be fantastic. If there are changes we need to make to the new core API however, I'm happy to make those.

**Comment by mitsuhiko** [comment]
I will make a proper review over the weekend. It's fine to only touch `minijinja` itself, i will update the other stuff. I think the best course of action will be a separate development branch for minijinja-2.

**Comment by mitsuhiko** [comment]
This generally looks pretty good. I think what I might do at that point is take this as a baseline on a longer running minijinja-2 branch and start hacking on it myself.

**Comment by mitsuhiko** [comment]
I'm tracking the things I'm running into in the issues labelled `minijinja-2`: https://github.com/mitsuhiko/minijinja/labels/minijinja-2

**Pull request merged**
