### PR TITLE
Added pluralize filter

### PR DESCRIPTION
**Pull request by epilys**
Reference
<https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#pluralize>

### CODE REVIEW

**Comment by epilys** [comment]
@mitsuhiko any particular reason why you removed string parsing? This behavior exists in both jinja2_pluralize and django's builtin filters, hence why I added it.

**Comment by mitsuhiko** [comment]
@epilys Pretty sure `jinja2_pluralize` applied to a string converts a english singular word to a plural word, not parse the string. Generally the string parsing seems like a footgun, so I rather not have it. If it's really needed I would wait until someone complains :)

**Comment by epilys** [comment]
It calls `int()` on the string: https://github.com/audreyfeldroy/jinja2_pluralize/blob/e94770417ff65c71461980ec26c5a1b4e4212ca5/jinja2_pluralize/__init__.py#L52

Django's impl calls `float()`: https://github.com/django/django/blob/255f5345904854128647705adcb8d21138e87c63/django/template/defaultfilters.py#L956

**Comment by mitsuhiko** [comment]
Either way I would prefer not to have that behavior.

**Pull request merged**
