### PR TITLE
rework minijinja to use values with references

### PR DESCRIPTION
**Pull request by SergioBenitez**
This is still a WIP, but putting it up now as I work through finishing the implementation.

This is a rather major change. The net effect is that Values can borrow, and you can recursively borrow for dynamic objects, resolving #160. Most of the internals use statically lived lifetimes, as before, at least for now. This needs to change, of course, to reap the full benefits. I believe this obviates the need for `minijinja-stack-ref`, but I'll need to take a closer look.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I will dive deeper into this over the next few days but some quite early comments of mine:

* Maybe it makes sense to leave the name `Value` for `ValueBox` and change what `Value<‘_>` at the moment is to `ValueRef<‘_>`. Motivation: it looks very much like that would be the smaller overall diff change. Would at the very least make it easier to review, but also it might be that most public uses remain the box version? Unclear
* Since the motivation is to borrow from non borrowed values, how would maintaining those borrows on the vm stack work?
* In practical terms the engine would need to support returning owned values from `get_field` and friends. Would this imply that the return value turns into an enum with both (borrow & owned) versions?
* I would separate out the struct to map change. I have created and removed that map type a few times now and I think if there is value in it, we can bring it back. However because at least right now many of the attribute accesses are from constant strings, the indirection via creating values produces quite a bit of unnecessary overhead.

**Comment by SergioBenitez** [comment]
> I will dive deeper into this over the next few days but some quite early comments of mine:
> 
> * Maybe it makes sense to leave the name `Value` for `ValueBox` and change what `Value<‘_>` at the moment is to `ValueRef<‘_>`. Motivation: it looks very much like that would be the smaller overall diff change. Would at the very least make it easier to review, but also it might be that most public uses remain the box version? Unclear

I went back and forth on this myself. I settled on `ValueBox` only to make it clear that it contained owned/allocated values. But the alternative is fine too, except that  `ValueRef` to me implies that it only contains references but it can in fact contain allocated values.

> * Since the motivation is to borrow from non borrowed values, how would maintaining those borrows on the vm stack work?

I have no idea. Theoretically, we annotate things the right way and things just work. In practice, there's a lot going on with the VM stack and associated code, and as of yet I've been unaable to remove allocations/cloning there. In fact, even a minimal example with a `MapObject` with this PR using all of the reference-based additions here results in 6 (!!) deep clones of the map object to retrieve a single nested value `map.key.value`, which is contrary to the entire point of this PR. So, so far, we don't have any performance wins, though the interface is much nicer.

Part of the problem is in the generic implementations for `Vec` and `HashMap`. I should be able to fix these such that the default implementation is the efficient one, even if it doesn't work as universally and one might hope. We'd need specialization for that. Once I do that, we'll see if we get closer to the 0 allocations we're looking for.

> * In practical terms the engine would need to support returning owned values from `get_field` and friends. Would this imply that the return value turns into an enum with both (borrow & owned) versions?

No, this is just `Value<'_>`, and I've already made that change to my offline branch.

> * I would separate out the struct to map change. I have created and removed that map type a few times now and I think if there is value in it, we can bring it back. However because at least right now many of the attribute accesses are from constant strings, the indirection via creating values produces quite a bit of unnecessary overhead.

Keeping the owned map in `Value` significantly complicates making this change. While this does introduce one new level of pointer indirection, it also removes an expensive one by getting rid of `KeyRef`, which obviates the need for interning whenever the string is a reference. I would guess that this implementation is much faster overall, but I haven't done any measurement. Certainly, the implementation is much simpler, and lots of deduplication is removed. It also makes the `Value` model very clear. Overall, I've found this change in particular to be an incredible win when it comes to internal ergonomics and clarity, and I would advocate for its inclusion whether or not the remaining changes make it in.

**Comment by SergioBenitez** [comment]
For posterity: the goal of this PR so that accesses like `foo.bar.baz.a.b.c.value` (written this way or any other way), where `foo`, `bar`, `baz`, `a`, `b`, and `c` are all user defined `Object`s which may be large maps or vectors or structs, incurs at most one allocation/clone of the final `value`. If that value is `Copy`, then the clone is effectively free, and no additional overhead is incurred. We are not there yet, but this PR certainly lays the foundation for that.

**Comment by SergioBenitez** [comment]
Closed in favor of #400.

**Pull request closed without merging**
