### PR TITLE
Expose render functions taking Value and std::fmt::Write

### PR DESCRIPTION
**Pull request by brendanhay**
### Rendering Values

The currently exposed api for manipulating `Value` is public, which is useful - but alas the `Template::render/render_to_write` functions only take `impl Serialize`. This means that if you attempt manipulate `Value` directly in your own code, you may go through `Serialize` twice (I'm unclear). But even if you don't necessarily pay for serde's costs twice, it's still unweidly to monomorphise `Template::render` code using a [non-generic inner function](https://www.possiblerust.com/pattern/non-generic-inner-functions), in your own application code, despite already having a `Value` at hand.

I've added functions of the form `pub fn render_value(&self, value: Value) -> Result<String, Error>`
to mirror the existing functionality, but taking a concrete `Value`.

### Rendering std::fmt::Write

The `render_to_write` function takes `std::io::Write`, which as the examples show is useful for writing to file/handle such as `stdout`. Unfortunately if one wanted to write to a buffer that supports UTF-8 such as `String`, you end up with:

```rust
{
    let tmpl = env.get_template("hello")?;
    let mut buf  = Vec::with_capacity(tmpl.source.len().next_power_of_two());

    template.render_to_write(context, &mut buf)?;

    buf.shrink_to_fit();

    // Or safe/checked, either way is unnecessary when we know we're writing a String.
    Ok(unsafe { String::from_utf8_unchecked(buf) })
}
```

I think ideally `render_to_write` would just take a `fmt::Write` and you could wrap the argument with `WriteWrapper` yourself, or have `render_io_write, render_fmt_write`, but in trying to keep backwards compatibility I've just added functions following the same naming convention, just a little more verbose: `pub fn render_to_fmt_write<S: Serialize, W: fmt::Write>(&self, ctx: S, w: &mut W) -> Result<(), Error>`, where `fmt_write` denotes `std::fmt` instead of `std::io`.

### Size Hints

The current `Template::render` function allocates via `String::new()` before rendering - from what I understand this causes  the underlying Vec to grow 1/2/4/8/16/etc. - A better default since we have the template's original source at hand is to use this as the initial capacity, via `String::with_capacity(self.compiled.source.len())`. I've made that change but also expose `Template::size_hint` for documentative purposes, more than anything. It could also be modified to provide a less conservative base hint and more of a guesstimate if someone has a better default heuristic.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
> This means that if you attempt manipulate Value directly in your own code, you may go through Serialize twice (I'm unclear). But even if you don't necessarily pay for serde's costs twice, it's still unweidly to monomorphise Template::render code using a [non-generic inner function](https://www.possiblerust.com/pattern/non-generic-inner-functions), in your own application code, despite already having a Value at hand.

There is a short path for a value passed as `Serialize` and if you already have a value, it should monomorphise into a single version of that across all your uses. You should not notice the extra cost or code bloat here.

> A better default since we have the template's original source at hand is to use this as the initial capacity

I don't think there is a good relationship of the template's source length to the output. At least it does not make a lot of sense to me that there would be. Often outputs are much smaller than the template code (eg: macros are used), sometimes they are much larger (eg: loops are used).

I would prefer not to duplicate these APIs unless absolutely necessary.

**Comment by mitsuhiko** [comment]
I added clarifications to the render functions that passing `Value` is supported and efficient and will close this PR.

**Comment by brendanhay** [comment]
Thanks for the clarification on Serialize/Value.

You didn't address the example above with the existing `render_to_write` api and `fmt::Write`, though. I'm still forced to use a `Vec<u8> as io::Write` and perform UTF8 conversion to get a `String`.

Regarding size hints, it's fine if it doesn't make sense to you and you don't want to include it by default - but it is a measurable difference in actual (non micro) benchmarks with templates on the order of 4000-8000+ bytes. Starting with a buffer size of 0 means you're going to resize _many_ times. I implore you to at least make writing to UTF8 buffers without added conversion possible, so we can do it ourselves.

For reference, I encourage you to read how other templating engines do it:

* [ramhorns](https://github.com/maciejhirsz/ramhorns/blob/ec36358867004ced292ecfd5ef0d41656955ab2b/ramhorns/src/template/mod.rs#L81-L94)
* [markup](https://github.com/utkarshkukreti/markup.rs/blob/5472ba9b04cef6578dc4699ce2dbf9bd5c83ed28/markup-proc-macro/src/generate.rs#L44-L49)
* [maud](https://github.com/lambda-fairy/maud/blob/1fff8123ebdaa093f6129867e6f5b3917129c183/maud_macros/src/lib.rs#L33)
* [sailfish](https://github.com/rust-sailfish/sailfish/blob/b293756277b751d3ef1ebf426748795fae795e8f/sailfish-compiler/src/procmacro.rs#L264-L268)

Ramhorns in particular is interesting because it is also runtime/dynamic - but it builds the size/capacity hint during parsing by ignoring templating syntax - so it gives you at a minimum the source that will be rendered, which is a considerably better starting point than 0.

**Comment by mitsuhiko** [comment]
I guess on the question of the `Vec<u8>` buffer I’m guessing your goal is to reuse buffers for repeated rendering? In general there is already an API to render straight into a string which doesn’t require any utc-8 validation.

Maybe you could open an issue for the specific issues you think need resolving. There is also a benchmark suite you could test your theory on.

**Pull request closed without merging**
